import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"; // Para notificaciones
import { SessionProvider } from "next-auth/react"; // Importamos el proveedor de sesión

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className="scroll-smooth">
      <body className={inter.className}>
        <SessionProvider> {/* Proveedor de sesión para toda la app */}
          <Toaster /> {/* Notificaciones */}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}